import os

GENIUS_CLIENT_ID: str = os.environ["GENIUS_CLIENT_ID"]
GENIUS_CLIENT_SECRET: str = os.environ["GENIUS_CLIENT_SECRET"]
GENIUS_REDIRECT_URI: str = os.environ["GENIUS_REDIRECT_URI"]
LASTFM_API_KEY: str = os.environ["LASTFM_API_KEY"]
SPOTIFY_CLIENT_ID: str = os.environ["SPOTIFY_CLIENT_ID"]
SPOTIFY_CLIENT_SECRET: str = os.environ["SPOTIFY_CLIENT_SECRET"]
SPOTIFY_REDIRECT_URI: str = os.environ["SPOTIFY_REDIRECT_URI"]
